# Generated by Django 5.1.6 on 2025-02-21 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ivw', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('1', 'Active'), ('0', 'Unactive')], default='1', max_length=1),
        ),
    ]
