# Generated by Django 5.1.6 on 2025-02-21 16:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ivw', '0005_stakeholder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('demand_id', models.AutoField(primary_key=True, serialize=False)),
                ('insertion_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
    ]
