# Generated by Django 5.1.6 on 2025-02-23 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ivw', '0008_rename_beneficiaries_scale_demand_potential_beneficiaries_scale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sdg',
            name='id',
        ),
        migrations.AlterField(
            model_name='sdg',
            name='sdg_number',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False),
        ),
    ]
