# Generated by Django 5.1.6 on 2025-02-24 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ivw', '0010_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='demand',
            name='analysis_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TemporaryDemandStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Aguardando Priorização', 'Aguardando Priorização'), ('Aprovada', 'Aprovada'), ('Cancelada', 'Cancelada')], max_length=30)),
                ('demand', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ivw.demand')),
            ],
        ),
    ]
