# Generated by Django 5.1.6 on 2025-02-26 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ivw', '0011_demand_analysis_date_temporarydemandstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand',
            name='status',
            field=models.CharField(default='Aguardando Análise', max_length=50),
        ),
        migrations.CreateModel(
            name='ActionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('responsible', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('scope_detail', models.TextField()),
                ('estimated_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('demand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_plans', to='ivw.demand')),
            ],
        ),
    ]
