# Generated by Django 5.1.6 on 2025-02-27 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ivw', '0014_demand_program_alter_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryDemandProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demand', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ivw.demand')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ivw.program')),
            ],
        ),
    ]
