# Generated by Django 5.1.6 on 2025-02-28 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ivw', '0015_temporarydemandprogram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionplan',
            name='status',
            field=models.CharField(default='Pendent', max_length=50),
        ),
        migrations.AlterField(
            model_name='demand',
            name='status',
            field=models.CharField(default='Awaiting analysis', max_length=50),
        ),
        migrations.AlterField(
            model_name='temporarydemandstatus',
            name='status',
            field=models.CharField(choices=[('Awaiting Prioritization', 'Awaiting Prioritization'), ('Approved', 'Approved'), ('Canceled', 'Canceled')], max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='active',
            field=models.CharField(choices=[('A', 'Active'), ('I', 'Inactive')], default='A', max_length=1),
        ),
    ]
